# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-28 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('input_images', models.CharField(blank=True, max_length=10000, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_images', models.CharField(blank=True, max_length=10000, null=True)),
                ('socket_id', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'questionanswer',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('placeholder', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_of_images', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Tasks'),
        ),
    ]
