# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-04-05 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='example',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
